### ISSUE TITLE
Defining Multiple Message Type

### ISSUE THREAD

**Issue by GHR-Arash** [sammccord/sc-codec-pbf#1]
`.setCodecEngine(new scCodecPbf(Example));`
just set one message Type
how can i set multiple message type in scCodecPbf ?

**Comment by sammccord** [comment]
This library isn't intended to work with multiple message types, the idea being that you would send and receive typed atomic actions that modify state, like an action in a redux reducer, which could be expressed in one proto message.

I bet you could use reference this library, and have flags in your messages that determine what proto message to encode/decode with.

Closing since topic is out of scope.
